/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const SettingsLazyRouteImport = createFileRoute('/settings')()
const ProjectsLazyRouteImport = createFileRoute('/projects')()
const PortalLazyRouteImport = createFileRoute('/portal')()
const FinanceLazyRouteImport = createFileRoute('/finance')()
const DocumentsLazyRouteImport = createFileRoute('/documents')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const CrmLazyRouteImport = createFileRoute('/crm')()
const AssetsLazyRouteImport = createFileRoute('/assets')()
const AnalyticsLazyRouteImport = createFileRoute('/analytics')()

const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ProjectsLazyRoute = ProjectsLazyRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))
const PortalLazyRoute = PortalLazyRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/portal.lazy').then((d) => d.Route))
const FinanceLazyRoute = FinanceLazyRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/finance.lazy').then((d) => d.Route))
const DocumentsLazyRoute = DocumentsLazyRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/documents.lazy').then((d) => d.Route))
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const CrmLazyRoute = CrmLazyRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/crm.lazy').then((d) => d.Route))
const AssetsLazyRoute = AssetsLazyRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/assets.lazy').then((d) => d.Route))
const AnalyticsLazyRoute = AnalyticsLazyRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/analytics.lazy').then((d) => d.Route))
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/crm': typeof CrmLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/documents': typeof DocumentsLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/portal': typeof PortalLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/crm': typeof CrmLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/documents': typeof DocumentsLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/portal': typeof PortalLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/crm': typeof CrmLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/documents': typeof DocumentsLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/portal': typeof PortalLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/analytics'
    | '/assets'
    | '/crm'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/portal'
    | '/projects'
    | '/settings'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/analytics'
    | '/assets'
    | '/crm'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/portal'
    | '/projects'
    | '/settings'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/analytics'
    | '/assets'
    | '/crm'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/portal'
    | '/projects'
    | '/settings'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AnalyticsLazyRoute: typeof AnalyticsLazyRoute
  AssetsLazyRoute: typeof AssetsLazyRoute
  CrmLazyRoute: typeof CrmLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  DocumentsLazyRoute: typeof DocumentsLazyRoute
  FinanceLazyRoute: typeof FinanceLazyRoute
  PortalLazyRoute: typeof PortalLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AnalyticsLazyRoute: AnalyticsLazyRoute,
  AssetsLazyRoute: AssetsLazyRoute,
  CrmLazyRoute: CrmLazyRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  DocumentsLazyRoute: DocumentsLazyRoute,
  FinanceLazyRoute: FinanceLazyRoute,
  PortalLazyRoute: PortalLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
